<!DOCTYPE html>
<html>
<head>
    <title>Login</title>

</head>
<body align ="center">

<header >
    <div id="menu">
        <ul fr>
            <li><a href="/registration"><h2>Регистрация</h2></a></li>

        </ul>
    </div>
</header>

<br>
<br>
<br>
<form action="/login" method="post">
    <h3>
        Login<input type="text" name="username">
        <br>
        <br>
        Password<input type="password" name="password">
        <br>
        <br>
        <input type="submit" value="Войти" class="button2">
    </h3>
</form>
</body>
</html>