create table contacts
(
    id              bigint generated by default as identity,
    name            varchar(255),
    contact_type_id bigint,
    user_id         bigint,
    primary key (id)
);

create table contacts_type
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

alter table if exists contacts
    add constraint FK_contact_contact_type foreign key (contact_type_id) references contacts_type;
alter table if exists contacts
    add constraint FK_contact_user foreign key (user_id) references users;