alter table if exists product
    add column product_category_id bigint;

create table product_category
(
    id       bigint generated by default as identity,
    name     varchar(255),
    priority int,
    primary key (id)
);

alter table if exists product
    add constraint FK_product_product_category foreign key (product_category_id) references product_category;